version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: simplestorage_postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simplestorage_network

  backend:
    build: ./backend
    container_name: simplestorage_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      - simplestorage_network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

networks:
  simplestorage_network:
    driver: bridge