"""add sequence for size display_order

Revision ID: 6948ed647650
Revises: a2224e014f76
Create Date: 2025-09-30 20:06:33.872825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6948ed647650'
down_revision: Union[str, Sequence[str], None] = 'a2224e014f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE size_display_order_seq")
    op.execute("ALTER TABLE sizes ALTER COLUMN display_order SET DEFAULT nextval('size_display_order_seq')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sizes ALTER COLUMN display_order DROP DEFAULT")
    op.execute("DROP SEQUENCE size_display_order_seq")
    # ### end Alembic commands ###
